// Browser PDF generation: opens a print page with one applicant per page.
import { allReadonly } from "./core.js";
import { sirFileBaseFromState } from "./importExport.js";

const PDF_DISCLAIMER = "Disclaimer: This is not an official mapping or government form. This PDF is only generated by a helper tool for data entry.";
const OFFLINE_WARNING = "Copy these details in original form.\nSubmit your original form to BLO.";

function esc(value) {
  return String(value ?? "").replace(/[&<>"']/g, ch => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;"
  }[ch]));
}

function cleanText(value) {
  return String(value ?? "").replace(/[\r\n\t]+/g, " ").replace(/\s{2,}/g, " ").trim();
}

function formatDateForDisplay(value) {
  const raw = String(value || "").trim();
  const m = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (m) return `${m[3]}-${m[2]}-${m[1]}`;
  return raw;
}

function safePhotoSrc(value) {
  const src = String(value || "");
  return /^data:image\/(png|jpe?g|webp);base64,/i.test(src) ? src : "";
}

function field(label, value) {
  return `
    <div class="read-field">
      <span class="read-label" aria-hidden="true">${esc(label)}</span>
      <span class="read-value">${esc(cleanText(value))}</span>
    </div>`;
}

function acPartSerialTable(ac, part, sl) {
  return `
    <table class="ac-table">
      <thead><tr><th>AC no</th><th>Part no</th><th>Sl no</th></tr></thead>
      <tbody><tr><td>${esc(cleanText(ac))}</td><td>${esc(cleanText(part))}</td><td>${esc(cleanText(sl))}</td></tr></tbody>
    </table>`;
}

function dobDigits(dateValue) {
  const raw = String(dateValue || "");
  const m = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  const value = m ? `${m[3]}${m[2]}${m[1]}` : raw.replace(/\D/g, "").slice(0, 8);
  return value.padEnd(8, " ").slice(0, 8).split("");
}

function dobCells(dateValue) {
  return `<div class="dob-cells">${dobDigits(dateValue).map(d => `<span>${esc(d)}</span>`).join("")}</div>`;
}

function onlinePage(data) {
  const photo = safePhotoSrc(data["Photo Data"]);
  return `
    <section class="page">
      <div class="online-head">
        <h1>${esc(data.applicant_name || "Applicant")}</h1>
        ${photo ? `<img class="online-photo" src="${esc(photo)}" alt="Applicant photo">` : ""}
      </div>
      <div class="pdf-disclaimer">${esc(PDF_DISCLAIMER)}</div>
      <section class="read-section top-grid">
        ${field("EPIC ID", data["EPIC ID"])}
        ${field("Phone Number", data["Phone Number"])}
      </section>
      <section class="read-section">
        <h2>Mapping Details</h2>
        <div class="read-line two">
          ${field("Type", data["Mapping Type"])}
          ${field("Relationship", data["Mapping Relation"])}
        </div>
        <div class="read-line four">
          ${field("Mapper Name", data["Mapper Name as per 2002"] || data["Mapping Name"])}
          ${field("2002 EPIC Number", data["Mapper 2002 EPIC Number"])}
          ${field("Relative", data["Mapper Relative Name"])}
          ${field("Relation with Relative", data["Mapper Relationship with Relative"])}
        </div>
        <div class="read-line two">
          ${field("State", data["Mapping State"])}
          ${field("District", data["Mapping District"])}
        </div>
        <div class="read-line three">
          ${field("AC No", data["Mapping AC No Display"])}
          ${field("Part No", data["Mapping Part No"])}
          ${field("Sl No", data["Mapping Serial No"])}
        </div>
      </section>
      <section class="read-section">
        <h2>Applicant Details</h2>
        <div class="read-line two">
          ${field("Date of Birth", formatDateForDisplay(data["Date of Birth"]))}
          ${field("Aadhaar Number", data["Aadhaar Number"])}
        </div>
        <h3>Father</h3>
        <div class="read-line two">${field("Name", data["Father’s Name"])}${field("EPIC Number", data["Father’s EPIC Number"])}</div>
        <h3>Mother</h3>
        <div class="read-line two">${field("Name", data["Mother’s Name"])}${field("EPIC Number", data["Mother’s EPIC Number"])}</div>
        <h3>Spouse</h3>
        <div class="read-line two">${field("Name", data["Spouse’s Name"])}${field("EPIC Number", data["Spouse’s EPIC Number"])}</div>
      </section>
    </section>`;
}

function offlineMappingColumn(title, data, shouldFill) {
  const value = label => shouldFill ? cleanText(data[label]) : "";
  const relation = shouldFill ? cleanText(data["Mapping Relation"]) : "";
  const mapperName = value("Mapper Name as per 2002");
  const showRelation = relation && relation !== "Self";
  const mapperNameWithRelation = mapperName && showRelation ? `${mapperName} (${relation})` : mapperName;
  return `
    <section class="offline-col">
      <h2>${esc(title)}</h2>
      ${field("Name as per 2002", mapperNameWithRelation)}
      ${field("Relative name", value("Mapper Relative Name"))}
      ${field("Relationship with relative", value("Mapper Relationship with Relative"))}
      ${field("District", value("Mapping District"))}
      ${field("State", value("Mapping State"))}
      ${field("AC name", value("Mapping AC Name"))}
      ${field("2002 EPIC number", value("Mapper 2002 EPIC Number"))}
      ${acPartSerialTable(value("Mapping AC No"), value("Mapping Part No"), value("Mapping Serial No"))}
    </section>`;
}

function offlineDetailRow(label, valueHtml) {
  return `
    <div class="offline-detail-row">
      <div class="offline-detail-label">${esc(label)}</div>
      <div class="offline-detail-value">${valueHtml}</div>
    </div>`;
}

function offlineDetailText(label, value) {
  return offlineDetailRow(label, `<span class="read-value">${esc(cleanText(value))}</span>`);
}

function offlineApplicantDetails(data) {
  return `
    <section class="read-section offline-details">
      <h2>Applicant Details</h2>
      <div class="offline-detail-grid">
        ${offlineDetailRow("Date of birth", dobCells(data["Date of Birth"]))}
        ${offlineDetailText("Aadhaar number", data["Aadhaar Number"])}
        ${offlineDetailText("Phone number", data["Phone Number"])}
        ${offlineDetailText("Father's name", data["Father’s Name"])}
        ${offlineDetailText("Father's EPIC number", data["Father’s EPIC Number"])}
        ${offlineDetailText("Mother's name", data["Mother’s Name"])}
        ${offlineDetailText("Mother's EPIC number", data["Mother’s EPIC Number"])}
        ${offlineDetailText("Spouse's name", data["Spouse’s Name"])}
        ${offlineDetailText("Spouse's EPIC number", data["Spouse’s EPIC Number"])}
      </div>
    </section>`;
}

function offlinePage(data) {
  const isSelf = data["Mapping Relation"] === "Self";
  const header = `${cleanText(data.applicant_name || "Applicant")} (${cleanText(data["EPIC ID"])})`;
  return `
    <section class="page offline-page">
      <h1>${esc(header)}</h1>
      <div class="pdf-disclaimer">${esc(PDF_DISCLAIMER)}</div>
      <div class="offline-warning">${esc(OFFLINE_WARNING).replace(/\n/g, "<br>")}</div>
      <div class="offline-two">
        ${offlineMappingColumn("Self Mapping", data, isSelf)}
        ${offlineMappingColumn("Parent Mapping", data, !isSelf)}
      </div>
      ${offlineApplicantDetails(data)}
    </section>`;
}

function openPdfWindow({ state, title, pagesHtml, mode = "online" }) {
  const fileBase = sirFileBaseFromState(state);
  const win = window.open("", "_blank");
  if (!win) throw new Error("Popup blocked. Please allow popups to generate PDF.");
  win.document.write(`<!doctype html><html><head><title>${fileBase}.pdf</title><style>
    @page { size:A4; margin:12mm; }
    * { box-sizing:border-box; }
    body { font-family:Arial,sans-serif; color:#17221d; margin:0; user-select:text; }
    .page { page-break-after:always; border:1px solid #dce8e2; border-radius:10px; padding:14px; }
    .page:last-child { page-break-after:auto; }
    h1 { font-size:21px; margin:0 0 12px; color:#195b45; }
    h2 { font-size:15px; margin:0 0 8px; color:#195b45; }
    h3 { font-size:13px; margin:10px 0 5px; color:#65736d; }
    .online-head { display:flex; justify-content:space-between; gap:12px; align-items:flex-start; margin-bottom:8px; }
    .online-photo { width:95px; height:115px; object-fit:cover; border:1px solid #dce8e2; border-radius:6px; }
    .pdf-disclaimer,.offline-warning { border:1px solid #f0d58a; background:#fff8df; color:#5d4300; font-weight:700; padding:6px 8px; margin:0 0 10px; }
    .pdf-disclaimer { font-size:10.5px; }
    .offline-warning { font-size:13px; line-height:1.45; text-align:center; font-weight:800; }
    .read-section { border-top:1px solid #dce8e2; padding-top:10px; margin-top:10px; }
    .read-section:first-of-type { border-top:0; padding-top:0; margin-top:0; }
    .read-line,.top-grid { display:grid; gap:8px; margin:6px 0; }
    .read-line.two,.top-grid { grid-template-columns:repeat(2,minmax(0,1fr)); }
    .read-line.three { grid-template-columns:repeat(3,minmax(0,1fr)); }
    .read-line.four { grid-template-columns:repeat(4,minmax(0,1fr)); }
    .read-field { display:grid; grid-template-columns:42% 58%; align-items:center; border:1px solid #dce8e2; min-height:34px; background:#fff; }
    .read-label { display:flex; align-items:center; height:100%; color:#65736d; font-weight:700; font-size:10.5px; padding:7px 8px; border-right:1px solid #dce8e2; background:#f6fbf8; }
    .read-value { display:inline-block; font-size:13.5px; overflow-wrap:anywhere; white-space:normal; padding:7px 8px; }
    .toolbar { position:sticky; top:0; z-index:5; background:#fff; border:1px solid #dce8e2; border-radius:8px; padding:8px; margin-bottom:10px; display:flex; gap:10px; align-items:center; font-size:12px; }
    .toolbar button { border:0; border-radius:8px; background:#195b45; color:#fff; padding:8px 10px; font-weight:700; }
    .offline-two { display:grid; grid-template-columns:1fr 1fr; gap:10px; margin-top:16px; }
    .offline-col { border:1px solid #dce8e2; border-radius:10px; padding:10px; min-height:360px; }
    .ac-table { width:100%; border-collapse:collapse; margin-top:6px; table-layout:fixed; }
    .ac-table th,.ac-table td { border:1px solid #dce8e2; padding:7px 8px; text-align:left; height:34px; }
    .ac-table th { color:#65736d; background:#f6fbf8; font-size:10.5px; }
    .offline-details { margin-top:18px; }
    .offline-detail-grid { display:grid; grid-template-columns:36% 64%; border:1px solid #dce8e2; border-radius:10px; overflow:hidden; }
    .offline-detail-row { display:contents; }
    .offline-detail-label,.offline-detail-value { border-bottom:1px solid #dce8e2; padding:7px 8px; min-height:34px; }
    .offline-detail-label { font-size:11px; font-weight:700; color:#65736d; background:#f6fbf8; }
    .offline-detail-value { font-size:13.5px; overflow-wrap:anywhere; }
    .dob-cells { display:grid; grid-template-columns:repeat(8,24px); }
    .dob-cells span { border:1px solid #17221d; border-left:0; height:26px; display:flex; align-items:center; justify-content:center; font-size:14px; }
    .dob-cells span:first-child { border-left:1px solid #17221d; }
    @media print { .no-print { display:none !important; } .page { border:0; padding:0; } }
  </style></head><body>
    <div class="no-print toolbar"><button id="copyAll">Copy all PDF text</button><span>${esc(title)}. Saved PDF text is selectable in most PDF viewers.</span></div>
    <main id="pdfContent" class="${esc(mode)}">${pagesHtml}</main>
    <script>
      function cleanPdfCopyText(value){return String(value||"").replace(/[\\r\\n\\t]+/g," ").replace(/\\s{2,}/g," ").trim();}
      document.getElementById("copyAll").addEventListener("click",async()=>{const text=Array.from(document.querySelectorAll("#pdfContent .read-value")).map(n=>cleanPdfCopyText(n.textContent)).filter(Boolean).join("\\n");try{await navigator.clipboard.writeText(text);alert("Copied clean PDF text.");}catch(err){const ta=document.createElement("textarea");ta.value=text;ta.setAttribute("readonly","readonly");ta.style.position="fixed";ta.style.left="-9999px";document.body.append(ta);ta.select();document.execCommand("copy");ta.remove();alert("Copied clean PDF text.");}});
    </script>
  </body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}

function pdfApplicants(state) {
  return (state.applicants || []).filter(a => a.export_to_pdf !== false);
}

export function generatePdf(state) {
  const rows = allReadonly(pdfApplicants(state), state.people);
  if (!rows.length) throw new Error("No applicants selected for PDF export.");
  openPdfWindow({ state, title: "Online Form PDF", pagesHtml: rows.map(onlinePage).join(""), mode: "online" });
}

export function generateOfflinePdf(state) {
  const rows = allReadonly(pdfApplicants(state), state.people);
  if (!rows.length) throw new Error("No applicants selected for PDF export.");
  openPdfWindow({ state, title: "Offline Form PDF", pagesHtml: rows.map(offlinePage).join(""), mode: "offline" });
}
